import { test } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs, { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { runInventory } from '../src/inventory/run.ts';
import { renderReport } from '../src/inventory/report.ts';
import { registrySchema } from '../src/schemas/registry.ts';
import { makeValidator } from '../src/schemas/validate.ts';
import { detectStack, proposeConfig } from '../src/detect/detect.ts';
import type { AppConfig } from '../src/config/config.ts';
import { main } from '../src/cli.ts';
import { stableStringify } from '../src/util/write.ts';
import { SKIP_DIRS } from '../src/util/fs-walk.ts';
import { tmpDir, withMocked, writeTree } from './helpers.ts';

function tinyApp(): string {
  const root = tmpDir();
  writeTree(root, {
    'package.json': '{"name":"tiny","dependencies":{"@mui/material":"^7.0.0","react":"^19.0.0"}}',
    'src/theme/index.ts': `import { createTheme } from '@mui/material/styles';\nexport const theme = createTheme({ spacing: 4 });`,
    'src/components/a/A.tsx': `import { Box, Typography } from '@mui/material';\nexport function A() { return <Box sx={{ p: 2, color: '#123456' }}><Typography>Hi</Typography></Box>; }`,
    'src/components/a/A.test.tsx': `test('a', () => {});`,
    'src/common/components/B.tsx': `import Chip from '@mui/material/Chip';\nexport const B = () => <Chip />;`,
  });
  return root;
}
const validateRegistry = makeValidator(registrySchema);

test('runInventory produces a schema-valid registry with theme-aware samples', () => {
  const root = tinyApp();
  const { registry, samples, report } = runInventory({ appRootAbs: root, cfg: proposeConfig(detectStack(root), root), git: false });
  assert.deepEqual(validateRegistry(registry), []);
  assert.deepEqual(registry.theme, { spacingUnit: 4, radiusUnit: 4, source: 'static' });
  assert.equal(registry.inputs.files, 3);
  assert.equal(registry.metrics.components, 2);
  assert.equal(samples.find((s) => s.property === 'p')?.px, 8);
  assert.equal(registry.modules.find((m) => m.module === 'a')?.testRatio, 1);
  assert.deepEqual(registry.components.map((c) => c.id), ['src/common/components/B.tsx#B', 'src/components/a/A.tsx#A']);
  assert.match(report, /^# Interface inventory: tiny/);
  assert.match(report, /## Module scorecard/);
});

test('runInventory is deterministic: two runs on one tree serialise to identical bytes', () => {
  const root = tinyApp();
  const cfg = proposeConfig(detectStack(root), root);
  const a = runInventory({ appRootAbs: root, cfg, git: false });
  const b = runInventory({ appRootAbs: root, cfg, git: false });
  assert.equal(stableStringify(a.registry), stableStringify(b.registry));
  assert.equal(stableStringify(a.samples), stableStringify(b.samples));
  assert.equal(a.report, b.report);
});

test('the inventory command writes registry, samples and report to --out', async () => {
  const root = tinyApp();
  const out = join(tmpDir(), 'inv');
  const lines: string[] = [];
  const code = await main(['inventory', '--app', root, '--out', out, '--no-git'], { out: (s) => { lines.push(s); }, err: () => {} });
  assert.equal(code, 0);
  for (const f of ['registry.json', 'samples.jsonl', 'report.md']) assert.ok(existsSync(join(out, f)), `${f} missing`);
  assert.match(lines[0], /^inventory: 3 files, 2 components/);
});

test('the report says it is generated, by which command and engine version, and carries no date', () => {
  const { report } = runInventory({ appRootAbs: tinyApp(), cfg: proposeConfig(detectStack(tinyApp()), tinyApp()), git: false });
  assert.deepEqual(report.split('\n').slice(0, 3), ['# Interface inventory: tiny', '', 'Generated by `design-studio inventory`, engine 0.1.0. Do not edit it by hand: re-run the command to refresh it.']);
  assert.doesNotMatch(report, /\b\d{4}-\d{2}-\d{2}\b/);
});

test('an invalid registry is never written: the command prints the errors and the out path and exits 1', async () => {
  const root = tinyApp();
  const out = join(tmpDir(), 'inv');
  const err: string[] = [];
  // A digest that is not 40 hex characters makes inputs.hash fail its schema pattern.
  const fake = () => ({ update() { return this; }, digest: () => 'not-a-sha1' });
  let code = -1;
  await new Promise<void>((done, fail) => {
    withMocked(crypto, 'createHash', fake, () => {
      main(['inventory', '--app', root, '--out', out, '--no-git'], { out: () => {}, err: (s) => { err.push(s); } }).then((c) => { code = c; done(); }, fail);
    });
  });
  assert.equal(code, 1);
  assert.equal(err[0], `inventory: the registry failed schema validation; nothing was written to ${out}`);
  assert.ok(err.some((e) => e.includes('/inputs/hash must match pattern')), err.join('\n'));
  assert.ok(!existsSync(out), 'nothing is written');
});

test('a malformed package.json is reported under UNVERIFIED', () => {
  const root = tinyApp();
  writeTree(root, { 'package.json': '{"name": "tiny",' });
  const { registry } = runInventory({ appRootAbs: root, cfg: cfgOf(root), git: false });
  assert.equal(registry.parseErrors.length, 1);
  assert.equal(registry.parseErrors[0].file, 'package.json');
  assert.match(registry.parseErrors[0].message, /^package\.json: /);
});

test('the inventory command needs a config or --out', async () => {
  const err: string[] = [];
  assert.equal(await main(['inventory', '--app', tinyApp()], { out: () => {}, err: (s) => { err.push(s); } }), 2);
  assert.match(err[0], /--out/);
});

// ---- Per-component families and quality ----

const BOX = `import { Box } from '@mui/material';`;
const cfgOf = (root: string, over: Partial<AppConfig> = {}): AppConfig => ({ ...proposeConfig(detectStack(root), root), ...over });
const run = (root: string, over: Partial<AppConfig> = {}) => runInventory({ appRootAbs: root, cfg: cfgOf(root, over), git: false });
const componentOf = (r: ReturnType<typeof run>, id: string) => {
  const c = r.registry.components.find((x) => x.id === id);
  assert.ok(c, `${id} not in the registry`);
  return c;
};

function familyApp(): string {
  const root = tmpDir();
  const card = `${BOX}\nexport function Card() {\n  return <Box sx={{ p: 1, m: 2, gap: 1 }}>x</Box>;\n}`;
  writeTree(root, {
    'package.json': '{"name":"fam","dependencies":{"@mui/material":"^7.0.0","react":"^19.0.0"}}',
    'src/components/a/Card.tsx': card,
    'src/components/b/Card.tsx': card,
    'src/components/c/Card.tsx': card,
    'src/components/d/Status.tsx': `import { Chip } from '@mui/material';\nexport function Tagged() {\n  const tones = { open: '#111111', won: '#222222', lost: '#333333' };\n  return <Chip sx={{ color: tones.open }} />;\n}\nexport function Plain() {\n  return <Chip />;\n}`,
    'src/components/e/Other.tsx': `export function Other() {\n  const tones = { a: '#aaaaaa', b: '#bbbbbb', c: '#cccccc' };\n  return <b>{tones.a}</b>;\n}`,
    'src/common/components/Dead.tsx': `export function Dead() { return <div>never used</div>; }`,
  });
  return root;
}

test('a repeated style block is attached to the component that holds it, next to its same-name family', () => {
  const r = run(familyApp());
  const blocks = r.registry.families.filter((f) => f.kind === 'repeated-style-block');
  assert.equal(blocks.length, 1);
  assert.equal(blocks[0].size, 3);
  for (const dir of ['a', 'b', 'c']) {
    assert.deepEqual(componentOf(r, `src/components/${dir}/Card.tsx#Card`).families, [blocks[0].key, 'same-name:Card']);
  }
});

test('a status map is attached to the component it sits inside, not to a sibling in the same file', () => {
  const r = run(familyApp());
  assert.deepEqual(componentOf(r, 'src/components/d/Status.tsx#Tagged').families, ['status-color-map:all']);
  assert.deepEqual(componentOf(r, 'src/components/d/Status.tsx#Plain').families, []);
  assert.deepEqual(componentOf(r, 'src/components/e/Other.tsx#Other').families, ['status-color-map:all']);
});

test('dead-shared still attaches to the component it names', () => {
  assert.deepEqual(componentOf(run(familyApp()), 'src/common/components/Dead.tsx#Dead').families, ['dead-shared:all']);
});

test('a file-level family attaches to every component in the file', () => {
  const root = tmpDir();
  const body = (a: string, b: string) => `${BOX}\nexport function ${a}() { return <Box>${'alpha '.repeat(20)}</Box>; }\nexport function ${b}() { return <Box>${'beta '.repeat(20)}</Box>; }`;
  writeTree(root, {
    'package.json': '{"name":"twin","dependencies":{"@mui/material":"^7.0.0"}}',
    'src/components/a/Pair.tsx': body('First', 'Second'),
    'src/components/b/Pair.tsx': body('First', 'Second'),
  });
  const r = run(root);
  const identical = r.registry.families.find((f) => f.kind === 'identical-files');
  assert.ok(identical);
  for (const dir of ['a', 'b']) {
    for (const name of ['First', 'Second']) {
      assert.ok(componentOf(r, `src/components/${dir}/Pair.tsx#${name}`).families.includes(identical.key), `${dir}/${name} lacks ${identical.key}`);
    }
  }
});

test('a module-scope status map attaches only to the component that references it', () => {
  const root = familyApp();
  writeTree(root, {
    'src/components/f/Tones.tsx': `import { Chip } from '@mui/material';\nconst STATUS_TONES = { open: 'success', won: 'info', lost: 'error' };\nexport function Uses({ s }: { s: 'open' }) {\n  return <Chip color={STATUS_TONES[s]} />;\n}\nexport function Ignores() {\n  return <Chip />;\n}`,
  });
  const r = run(root);
  assert.deepEqual(componentOf(r, 'src/components/f/Tones.tsx#Uses').families, ['status-color-map:all']);
  assert.deepEqual(componentOf(r, 'src/components/f/Tones.tsx#Ignores').families, []);
});

test('a module-scope status map or copy comment that no component references belongs to the whole file', () => {
  const root = familyApp();
  writeTree(root, {
    'src/components/f/Pair.tsx': `import { Chip } from '@mui/material';\n// copied from d/Status.tsx\nconst UNUSED_TONES = { open: 'success', won: 'info', lost: 'error' };\nexport function One() {\n  return <Chip />;\n}\nexport function Two() {\n  return <Chip />;\n}`,
  });
  const r = run(root);
  for (const name of ['One', 'Two']) assert.deepEqual(componentOf(r, `src/components/f/Pair.tsx#${name}`).families, ['copy-comment:all', 'status-color-map:all'], name);
});

test('a module-scope style const, or a makeStyles hook, counts in the quality of the components that use it', () => {
  const root = tmpDir();
  writeTree(root, {
    'package.json': '{"name":"q","dependencies":{"@mui/material":"^7.0.0"}}',
    'src/components/a/Cells.tsx': `${BOX}\nimport { makeStyles } from 'tss-react/mui';\nconst CELL_SX = { p: 1, color: '#123456', fontSize: 12 };\nconst useStyles = makeStyles()((theme) => ({ root: { marginTop: 12, padding: theme.spacing(1) } }));\nexport function Cell() {\n  return <Box sx={CELL_SX}>a</Box>;\n}\nexport function Styled() {\n  const { classes } = useStyles();\n  return <Box className={classes.root}>b</Box>;\n}\nexport function Other() {\n  return <Box>c</Box>;\n}`,
  });
  const r = run(root);
  assert.deepEqual(componentOf(r, 'src/components/a/Cells.tsx#Cell').quality, { rawValues: 2, themeValues: 1 });
  assert.deepEqual(componentOf(r, 'src/components/a/Cells.tsx#Styled').quality, { rawValues: 1, themeValues: 1 });
  assert.deepEqual(componentOf(r, 'src/components/a/Cells.tsx#Other').quality, { rawValues: 0, themeValues: 0 });
});

test('quality counts raw and theme style values inside each component only', () => {
  const root = tmpDir();
  writeTree(root, {
    'package.json': '{"name":"q","dependencies":{"@mui/material":"^7.0.0"}}',
    'src/components/a/Pair.tsx': `${BOX}\nexport function Plain() {\n  return <Box sx={{ p: 2 }}>a</Box>;\n}\nexport function Loud() {\n  return <Box sx={{ color: '#112233', p: '13px' }}>b</Box>;\n}`,
  });
  const r = run(root);
  assert.deepEqual(componentOf(r, 'src/components/a/Pair.tsx#Plain').quality, { rawValues: 0, themeValues: 1 });
  assert.deepEqual(componentOf(r, 'src/components/a/Pair.tsx#Loud').quality, { rawValues: 2, themeValues: 0 });
});

test('primitive prop values named like Object.prototype members are counted like any other value', () => {
  const root = tmpDir();
  writeTree(root, {
    'package.json': '{"name":"proto","dependencies":{"@mui/material":"^7.0.0"}}',
    'src/components/a/A.tsx': `import { Button } from '@mui/material';\nexport function A() { return <><Button variant="constructor" /><Button variant="toString" /><Button variant="__proto__" /><Button variant="constructor" /></>; }`,
  });
  const { registry } = run(root);
  const expected = JSON.parse('{"count":4,"props":{"variant":{"__proto__":1,"constructor":2,"toString":1}}}');
  assert.deepEqual(JSON.parse(stableStringify(registry)).primitives.Button, expected);
  assert.deepEqual(validateRegistry(registry), []);
});

test('the theme source is not counted as raw values, but its samples are kept', () => {
  const plain = tinyApp();
  const palette = tinyApp();
  writeTree(palette, {
    'src/theme/index.ts': `import { createTheme } from '@mui/material/styles';\nexport const theme = createTheme({ spacing: 4, palette: { primary: { main: '#abcdef' }, secondary: { main: '#fedcba' } } });`,
    'src/theme/tokens.ts': `export const BRAND = { ink: '#010203', paper: '#f0f0f0' };`,
    'src/theme/Swatch.tsx': `import { Box } from '@mui/material';\nexport function Swatch() { return <Box sx={{ color: '#0a0b0c', p: 1 }} />; }`,
  });
  const a = run(plain).registry;
  const r = run(palette);
  const b = r.registry;
  assert.deepEqual([b.metrics.distinct, b.metrics.tokenCoverage], [a.metrics.distinct, a.metrics.tokenCoverage]);
  assert.deepEqual(b.modules.map((m) => [m.module, m.samples, m.rawPerKloc > 0, m.tokenDiscipline]), a.modules.map((m) => [m.module, m.samples, m.rawPerKloc > 0, m.tokenDiscipline]));
  assert.deepEqual(componentOf(r, 'src/theme/Swatch.tsx#Swatch').quality, { rawValues: 0, themeValues: 0 });
  assert.deepEqual(r.samples.filter((s) => s.file.startsWith('src/theme/') && s.kind === 'color').map((s) => s.raw), ['#0a0b0c', '#abcdef', '#fedcba', '#010203', '#f0f0f0']);
  assert.equal(b.metrics.samples, a.metrics.samples + 6);
});

test('more than 25 same-name files skip the near-duplicate check, and the report lists them', () => {
  const root = tmpDir();
  const card = (i: number) => `${BOX}\nexport function Card${i}() {\n  return <Box>${'card body text '.repeat(15)}${i}</Box>;\n}`;
  writeTree(root, {
    'package.json': '{"name":"cards","dependencies":{"@mui/material":"^7.0.0"}}',
    ...Object.fromEntries(Array.from({ length: 26 }, (_, i) => [`src/components/m${String(i).padStart(2, '0')}/Card.tsx`, card(i)])),
  });
  const { registry, report } = run(root);
  assert.equal(registry.families.filter((f) => f.kind === 'near-duplicate-files').length, 0);
  assert.ok(report.includes('## Skipped checks\n\n- Near-duplicate comparison skipped for the 26 files named `Card.tsx` (more than 25 share the name)\n'), report);
  assert.doesNotMatch(run(tinyApp()).report, /Skipped checks/);
});

// ---- A file that cannot be analysed never stops the run ----

function brokenApp(): string {
  const root = tinyApp();
  writeTree(root, { 'src/components/a/Broken.tsx': 'export function Broken( { return <div>; }' });
  return root;
}

test('a file that cannot be parsed is reported as UNVERIFIED and the run carries on', () => {
  const { registry, report } = run(brokenApp());
  assert.deepEqual(validateRegistry(registry), []);
  assert.equal(registry.parseErrors.length, 1);
  assert.equal(registry.parseErrors[0].file, 'src/components/a/Broken.tsx');
  assert.match(registry.parseErrors[0].message, /^parse: /);
  assert.equal(registry.metrics.files, 4);
  assert.equal(registry.metrics.components, 2);
  assert.match(report, /## Files that could not be read or analysed \(UNVERIFIED\)/);
  assert.match(report, /`src\/components\/a\/Broken\.tsx`: parse: /);
});

// readFileSync, except that reading B.tsx fails with `message`.
function failReadingB(message: string): (...a: unknown[]) => unknown {
  const real = fs.readFileSync as (...a: unknown[]) => unknown;
  return (p, ...rest) => {
    if (String(p).endsWith('B.tsx')) throw new Error(message);
    return real(p, ...rest);
  };
}

test('a file that cannot be read is reported and the run carries on', () => {
  const root = tinyApp();
  const cfg = cfgOf(root);
  withMocked(fs, 'readFileSync', failReadingB('EACCES: permission denied\nsecond line'), () => {
    const { registry } = runInventory({ appRootAbs: root, cfg, git: false });
    assert.deepEqual(registry.parseErrors, [{ file: 'src/common/components/B.tsx', message: 'read: EACCES: permission denied' }]);
    assert.deepEqual(registry.components.map((c) => c.id), ['src/components/a/A.tsx#A']);
    assert.equal(registry.metrics.files, 3);
    assert.deepEqual(validateRegistry(registry), []);
  });
});

test('a folder that cannot be listed is reported once, app-relative, and the run carries on', () => {
  const root = tinyApp();
  const cfg = cfgOf(root);
  const real = fs.readdirSync as (...a: unknown[]) => unknown;
  const failing = join('src', 'components', 'a');
  withMocked(fs, 'readdirSync', (p, ...rest) => {
    if (String(p).endsWith(failing)) throw new Error(`EACCES: permission denied, scandir '${String(p)}'\nmore`);
    return real(p, ...rest);
  }, () => {
    const { registry, report } = runInventory({ appRootAbs: root, cfg, git: false });
    assert.deepEqual(registry.parseErrors, [{ file: 'src/components/a/', message: "read: EACCES: permission denied, scandir 'src/components/a'" }]);
    assert.deepEqual(registry.components.map((c) => c.id), ['src/common/components/B.tsx#B']);
    assert.deepEqual(validateRegistry(registry), []);
    assert.match(report, /`src\/components\/a\/`: read: EACCES/);
  });
});

test('a file that fails during analysis is reported as such and the run carries on', () => {
  const root = tinyApp();
  const cfg = cfgOf(root);
  // Only the first hash taken fails, and that is the first analysed file's, so exactly one file fails whatever order the stages run in.
  const real = crypto.createHash as (...a: unknown[]) => unknown;
  let calls = 0;
  withMocked(crypto, 'createHash', (...a) => { if (calls++ === 0) throw new Error('boom'); return real(...a); }, () => {
    const { registry } = runInventory({ appRootAbs: root, cfg, git: false });
    assert.equal(registry.parseErrors.length, 1);
    assert.match(registry.parseErrors[0].message, /^analyse: boom$/);
    assert.equal(registry.metrics.files, 3);
    assert.deepEqual(validateRegistry(registry), []);
  });
});

test('an error message never carries the absolute app root', () => {
  const root = tinyApp();
  const cfg = cfgOf(root);
  const b = join(root, 'src', 'common', 'components', 'B.tsx');
  const message = `EACCES: permission denied, open '${b}' (also ${b.replace(/\\/g, '/')} under ${root})`;
  withMocked(fs, 'readFileSync', failReadingB(message), () => {
    const { registry, report } = runInventory({ appRootAbs: root, cfg, git: false });
    assert.deepEqual(registry.parseErrors, [{ file: 'src/common/components/B.tsx', message: "read: EACCES: permission denied, open 'src/common/components/B.tsx' (also src/common/components/B.tsx under .)" }]);
    for (const text of [stableStringify(registry), report]) {
      assert.ok(!text.includes(root) && !text.includes(root.replace(/\\/g, '/')), 'the absolute root leaked');
    }
  });
});

// ---- A theme entry that cannot be used is never silent ----

const themeApp = (files: Record<string, string>): string => {
  const root = tinyApp();
  writeTree(root, files);
  return root;
};
const themeErrors = (r: ReturnType<typeof run>) => r.registry.parseErrors.filter((e) => e.message.endsWith('; library defaults used'));
const DEFAULTS = { spacingUnit: 8, radiusUnit: 4, source: 'default' };

test('a configured theme entry that does not exist is reported and defaults are used', () => {
  const r = run(tinyApp(), { themeEntry: 'src/theme/missing.ts' });
  assert.deepEqual(r.registry.theme, DEFAULTS);
  assert.deepEqual(themeErrors(r), [{ file: 'src/theme/missing.ts', message: 'read: file not found; library defaults used' }]);
  assert.match(r.report, /library defaults; the configured theme entry could not be used, see UNVERIFIED/);
  assert.match(r.report, /`src\/theme\/missing\.ts`: read: file not found; library defaults used/);
  assert.deepEqual(validateRegistry(r.registry), []);
});

test('a configured theme entry that is a directory is reported and defaults are used', () => {
  const r = run(tinyApp(), { themeEntry: 'src/theme' });
  assert.deepEqual(r.registry.theme, DEFAULTS);
  assert.equal(r.registry.metrics.components, 2);
  assert.equal(themeErrors(r).length, 1);
  assert.match(themeErrors(r)[0].message, /^read: EISDIR.*; library defaults used$/);
  assert.equal(themeErrors(r)[0].file, 'src/theme');
  assert.match(r.report, /configured theme entry could not be used/);
});

test('a configured theme entry that does not parse is reported and defaults are used', () => {
  const r = run(themeApp({ 'src/theme/broken.ts': 'export const theme = createTheme({ spacing: ;' }), { themeEntry: 'src/theme/broken.ts' });
  assert.deepEqual(r.registry.theme, DEFAULTS);
  assert.equal(themeErrors(r).length, 1);
  assert.equal(themeErrors(r)[0].file, 'src/theme/broken.ts');
  assert.match(themeErrors(r)[0].message, /^parse: .+; library defaults used$/);
  assert.match(r.report, /configured theme entry could not be used/);
});

test('a theme file that parses but sets no units stays clean', () => {
  const r = run(themeApp({ 'src/theme/index.ts': 'export const theme = createTheme({ palette: {} });' }), { themeEntry: 'src/theme/index.ts' });
  assert.deepEqual(r.registry.theme, DEFAULTS);
  assert.deepEqual(r.registry.parseErrors, []);
  assert.match(r.report, /library defaults; not set in the theme file/);
  assert.doesNotMatch(r.report, /could not be used/);
  assert.doesNotMatch(run(tinyApp(), { themeEntry: null }).report, /could not be used/);
});

test('a theme unit set in a form that cannot be read is reported under UNVERIFIED, whole or in part', () => {
  const whole = run(themeApp({ 'src/theme/index.ts': 'export const theme = createTheme({ spacing: (f: number) => f * 4 });' }), { themeEntry: 'src/theme/index.ts' });
  assert.deepEqual(whole.registry.theme, DEFAULTS);
  assert.deepEqual(whole.registry.parseErrors, [{ file: 'src/theme/index.ts', message: 'parse: spacing is set but not statically readable; library default used' }]);
  assert.match(whole.report, /library defaults; the configured theme entry could not be used, see UNVERIFIED/);
  const part = run(themeApp({ 'src/theme/index.ts': 'export const theme = createTheme({ spacing: SPACING, shape: { borderRadius: 6 } });' }), { themeEntry: 'src/theme/index.ts' });
  assert.deepEqual(part.registry.theme, { spacingUnit: 8, radiusUnit: 6, source: 'static' });
  assert.equal(part.registry.parseErrors.length, 1);
  assert.match(part.report, /spacing unit 8px, radius unit 6px \(read from the theme file in part; the rest are library defaults, see UNVERIFIED\)/);
});

test('with no theme entry configured the report says so', () => {
  const r = run(tinyApp(), { themeEntry: null });
  assert.match(r.report, /spacing unit 8px, radius unit 4px \(library defaults; no theme entry configured\)/);
  assert.deepEqual(r.registry.parseErrors, []);
});

// ---- Import resolution and inputs ----

test('the report counts non-relative imports that resolve to no file and name no dependency or Node builtin', () => {
  const root = tmpDir();
  writeTree(root, {
    'package.json': '{"name":"u","dependencies":{"react":"^19.0.0"},"devDependencies":{"vitest":"^3.0.0"},"peerDependencies":{"@scope/peer":"^1.0.0"}}',
    'tsconfig.json': '{ "compilerOptions": { "paths": { "@/ok/*": ["src/components/a/*"] } } }',
    'src/components/a/A.tsx': [
      "import React from 'react';",
      "import fs from 'node:fs';",
      "import path from 'path';",
      "import { readFile } from 'fs/promises';",
      "import { x } from '@/lib/missing';",
      "import { y } from 'not-installed/sub';",
      "import type { Z } from '@scope/peer/types';",
      "import { v } from 'vitest';",
      "import { local } from './local';",
      "import { aliased } from '@/ok/local';",
      "export * from '~/barrel';",
      "export function A() { return <div />; }",
    ].join('\n'),
    'src/components/a/local.ts': 'export const local = 1;',
  });
  assert.ok(run(root).report.includes('## Import resolution\n\n- 3 non-relative import specifier(s) resolve to no scanned file and are not a package.json dependency or a Node builtin: `@/lib/missing`, `not-installed/sub`, `~/barrel`\n'));
  assert.ok(run(tinyApp()).report.includes('## Import resolution\n\n- Every non-relative import resolves to a scanned file, a package.json dependency or a Node builtin.\n'));
});

test('at most ten unresolved specifiers are listed, sorted, beside the full count', () => {
  const root = tmpDir();
  const imports = Array.from({ length: 12 }, (_, i) => `import { x${i} } from '@/m${String(12 - i).padStart(2, '0')}';`).join('\n');
  writeTree(root, { 'package.json': '{"name":"many"}', 'src/components/a/A.tsx': `${imports}\nexport function A() { return <div />; }` });
  const line = run(root).report.split('\n').find((l) => l.startsWith('- 12 non-relative'));
  assert.ok(line);
  assert.ok(line.endsWith(`: ${Array.from({ length: 10 }, (_, i) => `\`@/m${String(i + 1).padStart(2, '0')}\``).join(', ')} (first 10 of 12)`), line);
});

test('inputs.hash covers the config, every tsconfig read and a theme entry outside the sources, with line endings normalised', () => {
  const root = tinyApp();
  writeTree(root, {
    'tsconfig.json': '{ "references": [{ "path": "./tsconfig.app.json" }] }',
    'tsconfig.app.json': '{ "compilerOptions": { "baseUrl": "." } }',
    'theme/outside.ts': 'export const theme = createTheme({ spacing: 4 });\n',
  });
  const cfg = cfgOf(root, { themeEntry: 'theme/outside.ts' });
  const hash = (c: AppConfig = cfg): string => runInventory({ appRootAbs: root, cfg: c, git: false }).registry.inputs.hash;
  const seen = [hash()];
  const changed = (what: string, h: string): void => { assert.ok(!seen.includes(h), `${what} did not change the hash`); seen.push(h); };
  changed('the config', hash({ ...cfg, exclude: [...cfg.exclude, '**/never/**'] }));
  writeTree(root, { 'tsconfig.json': '{ "references": [{ "path": "./tsconfig.app.json" }], "include": ["src"] }' });
  changed('tsconfig.json', hash());
  const app = '{\n  "compilerOptions": { "baseUrl": "src" }\n}\n';
  const theme = 'export const theme = createTheme({\n  spacing: 6,\n});\n';
  writeTree(root, { 'tsconfig.app.json': app });
  changed('a referenced tsconfig', hash());
  writeTree(root, { 'theme/outside.ts': theme });
  changed('the theme entry', hash());
  const crlf = (s: string): string => s.replace(/\n/g, '\r\n');
  writeTree(root, { 'tsconfig.app.json': crlf(app), 'theme/outside.ts': crlf(theme) });
  assert.equal(hash(), seen[seen.length - 1], 'CRLF line endings changed the hash');
});

// ---- The command ----

test('the inventory command rejects an --app folder that does not exist', async () => {
  const err: string[] = [];
  const missing = join(tmpDir(), 'nope');
  assert.equal(await main(['inventory', '--app', missing, '--out', join(tmpDir(), 'o')], { out: () => {}, err: (s) => { err.push(s); } }), 2);
  assert.equal(err[0], `inventory: --app <dir> does not exist: ${resolve(missing)}`);
});

test('the inventory command flags unparseable files on its summary line', async () => {
  const lines: string[] = [];
  const out = join(tmpDir(), 'inv');
  assert.equal(await main(['inventory', '--app', brokenApp(), '--out', out, '--no-git'], { out: (s) => { lines.push(s); }, err: () => {} }), 0);
  assert.match(lines[0], /^inventory: 4 files, 2 components/);
  assert.match(lines[0], /\(1 file\(s\) UNVERIFIED: could not be read or analysed\)$/);
});

test('with --config the output defaults to <config dir>/inventory', async () => {
  const root = tinyApp();
  const cfgPath = join(root, 'design-system', 'design-studio.config.json');
  writeTree(root, { 'design-system/design-studio.config.json': JSON.stringify(cfgOf(root)) });
  const lines: string[] = [];
  const err: string[] = [];
  assert.equal(await main(['inventory', '--app', root, '--config', cfgPath, '--no-git'], { out: (s) => { lines.push(s); }, err: (s) => { err.push(s); } }), 0, err.join('\n'));
  for (const f of ['registry.json', 'samples.jsonl', 'report.md']) assert.ok(existsSync(join(root, 'design-system', 'inventory', f)), `${f} missing`);
  assert.match(lines[0], /^inventory: 3 files, 2 components/);
});

test('the config under <app>/design-system is found without --config', async () => {
  const root = tinyApp();
  writeTree(root, { 'design-system/design-studio.config.json': JSON.stringify(cfgOf(root)) });
  assert.equal(await main(['inventory', '--app', root, '--no-git'], { out: () => {}, err: () => {} }), 0);
  assert.ok(existsSync(join(root, 'design-system', 'inventory', 'registry.json')));
});

test('a --config outside design-system/ resolves appRoot from its own folder, and must agree with --app', async () => {
  const root = tinyApp();
  const cfgPath = join(root, 'configs', 'ds.json');
  const go = async (appRoot: string) => {
    writeTree(root, { 'configs/ds.json': JSON.stringify(cfgOf(root, { appRoot })) });
    const err: string[] = [];
    const lines: string[] = [];
    const code = await main(['inventory', '--app', root, '--config', cfgPath, '--no-git'], { out: (s) => { lines.push(s); }, err: (s) => { err.push(s); } });
    return { code, err, lines };
  };
  const ok = await go('..');
  assert.equal(ok.code, 0, ok.err.join('\n'));
  assert.match(ok.lines[0], /^inventory: 3 files, 2 components/);
  assert.ok(existsSync(join(root, 'configs', 'inventory', 'registry.json')));
  const off = await go('.');
  assert.equal(off.code, 2);
  assert.deepEqual(off.err, [`inventory: --app ${resolve(root)} does not match the config's app root ${resolve(root, 'configs')}`]);
});

test('a --config whose app root does not exist is rejected', async () => {
  const root = tinyApp();
  const cfgPath = join(root, 'design-system', 'design-studio.config.json');
  writeTree(root, { 'design-system/design-studio.config.json': JSON.stringify(cfgOf(root, { appRoot: 'gone' })) });
  const err: string[] = [];
  assert.equal(await main(['inventory', '--app', root, '--config', cfgPath, '--no-git'], { out: () => {}, err: (s) => { err.push(s); } }), 2);
  assert.equal(err[0], `inventory: app root does not exist: ${resolve(root, 'gone')}`);
  assert.ok(!existsSync(join(root, 'design-system', 'inventory')), 'nothing is written for a missing app root');
});

// ---- The report ----

const globs = (xs: readonly string[]): string => xs.map((x) => `\`${x}\``).join(', ');

test('the report says what was scanned and what was left out', () => {
  const root = tinyApp();
  const cfg = cfgOf(root);
  assert.ok(run(root).report.includes(`Scanned: ${globs(cfg.sources)}. Excluded: ${globs(cfg.exclude)}.`));
  assert.ok(run(root, { legacy: ['src/old/**'] }).report.includes(`Excluded: ${globs([...cfg.exclude, 'src/old/**'])}.`));
});

test('the scanned line also names the folders the walker always skips', () => {
  const line = run(tinyApp()).report.split('\n').find((l) => l.startsWith('Scanned:'));
  assert.ok(line);
  for (const dir of SKIP_DIRS) assert.ok(line.includes(`\`${dir}\``), `${dir} missing`);
  assert.match(line, /and any folder starting with a dot\.$/);
});

test('a pipe in a family key or note is escaped so the table row survives', () => {
  const root = tinyApp();
  const { registry } = run(root);
  const family = { key: 'near-duplicate-files:src/a.tsx|src/b.tsx', kind: 'near-duplicate-files' as const, size: 2, members: [{ file: 'src/a.tsx', line: null, name: null }, { file: 'src/b.tsx', line: null, name: null }], note: '90% similar | by shingles' };
  const text = renderReport({ ...registry, families: [family] }, cfgOf(root));
  assert.ok(text.includes('| `near-duplicate-files:src/a.tsx\\|src/b.tsx` | near-duplicate-files | 2 | 90% similar \\| by shingles |'), text);
});

test('report headings state the cap only when a list is cut short', () => {
  const root = tinyApp();
  const cfg = cfgOf(root);
  const { registry } = run(root);
  const short = renderReport(registry, cfg);
  assert.match(short, /^## Most-used components \(top 25 of 0\)$/m);
  assert.match(short, /^## Duplicate families$/m);
  const many = {
    ...registry,
    components: Array.from({ length: 31 }, (_, i) => ({ ...registry.components[0], id: `c${i}`, name: `C${i}`, importers: { files: i + 1, modules: [] } })),
    families: Array.from({ length: 31 }, (_, i) => ({ key: `k${String(i).padStart(2, '0')}`, kind: 'same-name' as const, size: 2, members: [{ file: 'x', line: 1, name: 'x' }], note: 'n' })),
  };
  const long = renderReport(many, cfg);
  assert.match(long, /^## Most-used components \(top 25 of 31\)$/m);
  assert.match(long, /^## Duplicate families \(largest 30 of 31\)$/m);
  assert.equal((long.match(/^\| C\d+ \|/gm) ?? []).length, 25);
  assert.equal((long.match(/^\| `k\d+` \|/gm) ?? []).length, 30);
});

test('empty report sections say None instead of printing a header-only table', () => {
  const root = tmpDir();
  writeTree(root, { 'package.json': '{"name":"bare"}', 'src/components/a/A.tsx': 'export const A = () => null;' });
  const { registry } = run(root);
  const text = renderReport({ ...registry, modules: [] }, cfgOf(root));
  for (const heading of ['Most-used components \\(top 25 of 0\\)', 'Promotion candidates', 'Duplicate families', 'Module scorecard']) {
    assert.match(text, new RegExp(`## ${heading}\\n\\n_None\\._\\n`), `${heading} should print _None._`);
  }
});
