import type { AppConfig } from '../config/config.ts';
import { cmp } from '../util/compare.ts';
import { SKIP_DIRS } from '../util/fs-walk.ts';
import type { Registry } from './registry.ts';
import type { UnresolvedImports } from './unresolved.ts';
import type { SkippedCheck } from './families.ts';

const TOP_COMPONENTS = 25;
const TOP_FAMILIES = 30;
const pct = (n: number | null): string => (n === null ? 'n/a' : `${Math.round(n * 100)}%`);
const esc = (s: string): string => s.replace(/\|/g, '\\|');
const globs = (xs: readonly string[]): string => (xs.length ? xs.map((x) => `\`${x}\``).join(', ') : '_none_');

/** What the run looked at (the scanned and excluded globs, the theme entry), and what it could not use. */
export type ReportContext = Pick<AppConfig, 'sources' | 'exclude' | 'legacy' | 'themeEntry'> & {
  /** Why the configured theme entry could not be used, wholly or in part, so library defaults stand in; null when nothing is wrong. */
  themeProblem?: string | null;
  /** Non-relative imports that resolve to nothing the run knows; omitted, the section is left out. */
  unresolved?: UnresolvedImports;
  /** Checks that were not run on some files (too many share a name), listed under "Skipped checks". */
  skipped?: readonly SkippedCheck[];
};

function themeNote(r: Registry, ctx: ReportContext): string {
  if (ctx.themeEntry === null) return 'library defaults; no theme entry configured';
  if (ctx.themeProblem) {
    return r.theme.source === 'static'
      ? 'read from the theme file in part; the rest are library defaults, see UNVERIFIED'
      : 'library defaults; the configured theme entry could not be used, see UNVERIFIED';
  }
  return r.theme.source === 'static' ? 'read from the theme file' : 'library defaults; not set in the theme file';
}

export function renderReport(r: Registry, ctx: ReportContext): string {
  const L: string[] = [];
  // A table under a heading, or `_None._` when there are no rows.
  const table = (head: string[], align: string[], rows: string[]): void => {
    if (rows.length === 0) { L.push('_None._'); return; }
    L.push(`| ${head.join(' | ')} |`, `|${align.join('|')}|`, ...rows);
  };
  // A generated file says so, and by which command (spec §11); no date, so unchanged inputs give identical bytes.
  L.push(`# Interface inventory: ${r.app.product}`, '');
  L.push(`Generated by \`design-studio inventory\`, engine ${r.engine}. Do not edit it by hand: re-run the command to refresh it.`, '');
  L.push(`${r.metrics.files} files · ${r.metrics.components} components · ${r.metrics.samples} style values · ${r.metrics.families} duplicate families`, '');
  L.push(`Scanned: ${globs(ctx.sources)}. Excluded: ${globs([...ctx.exclude, ...ctx.legacy])}. Skipped folders: ${globs([...SKIP_DIRS])} and any folder starting with a dot.`, '');
  L.push('## Components by atomic level', '', '| Level | Count |', '|---|---:|');
  for (const lv of ['page', 'template', 'organism', 'molecule', 'atom', 'layout'] as const) L.push(`| ${lv} | ${r.metrics.byLevel[lv]} |`);
  const used = [...r.components].filter((c) => c.importers.files > 0).sort((a, b) => b.importers.files - a.importers.files || cmp(a.id, b.id));
  L.push('', `## Most-used components (top ${TOP_COMPONENTS} of ${used.length})`, '');
  table(['Component', 'Level', 'Layer', 'Importing files', 'Modules', 'File'], ['---', '---', '---', '---:', '---:', '---'],
    used.slice(0, TOP_COMPONENTS).map((c) => `| ${esc(c.name)} | ${c.level} | ${c.layer} | ${c.importers.files} | ${c.importers.modules.length} | \`${c.file}:${c.line}\` |`));
  const promo = r.components.filter((c) => c.promotionCandidate);
  L.push('', '## Promotion candidates', '');
  if (promo.length === 0) L.push('_None._');
  for (const c of promo) L.push(`- **${esc(c.name)}** (${c.level}) in \`${c.file}\` is used by ${c.importers.modules.join(', ')}`);
  const fams = [...r.families].sort((a, b) => b.size - a.size || cmp(a.key, b.key));
  L.push('', fams.length > TOP_FAMILIES ? `## Duplicate families (largest ${TOP_FAMILIES} of ${fams.length})` : '## Duplicate families', '');
  table(['Family', 'Kind', 'Size', 'Note'], ['---', '---', '---:', '---'],
    fams.slice(0, TOP_FAMILIES).map((f) => `| \`${esc(f.key)}\` | ${f.kind} | ${f.size} | ${esc(f.note)} |`));
  const d = r.metrics.distinct;
  L.push('', '## Foundations in use', '');
  L.push(`- Token coverage: ${pct(r.metrics.tokenCoverage)} of colour, type, spacing, radius and shadow values use the theme`);
  L.push(`- Distinct values outside the theme: ${d.colors} colours, ${d.fontSizes} font sizes, ${d.radii} radii, ${d.spacing} spacing values, ${d.shadows} shadows`);
  L.push(`- Theme facts: spacing unit ${r.theme.spacingUnit}px, radius unit ${r.theme.radiusUnit}px (${themeNote(r, ctx)})`);
  L.push('', '## Module scorecard', '');
  table(['Module', 'Files', 'LOC', 'Components', 'Raw values per kLOC', 'Token discipline', 'i18n', 'Tests', 'Last commit'], ['---', '---:', '---:', '---:', '---:', '---:', '---:', '---:', '---'],
    r.modules.map((m) => `| ${esc(m.module)} | ${m.files} | ${m.loc} | ${m.components} | ${m.rawPerKloc} | ${pct(m.tokenDiscipline)} | ${pct(m.i18nCoverage)} | ${pct(m.testRatio)} | ${m.lastCommit ?? 'n/a'} |`));
  const u = ctx.unresolved;
  if (u) {
    L.push('', '## Import resolution', '');
    if (u.count === 0) L.push('- Every non-relative import resolves to a scanned file, a package.json dependency or a Node builtin.');
    else {
      const more = u.count > u.examples.length ? ` (first ${u.examples.length} of ${u.count})` : '';
      L.push(`- ${u.count} non-relative import specifier(s) resolve to no scanned file and are not a package.json dependency or a Node builtin: ${u.examples.map((s) => `\`${esc(s)}\``).join(', ')}${more}`);
    }
  }
  if (ctx.skipped?.length) {
    L.push('', '## Skipped checks', '');
    for (const s of ctx.skipped) L.push(`- Near-duplicate comparison skipped for the ${s.count} files named \`${esc(s.name)}\` (more than 25 share the name)`);
  }
  if (r.parseErrors.length) {
    L.push('', '## Files that could not be read or analysed (UNVERIFIED)', '');
    for (const e of r.parseErrors) L.push(`- \`${e.file}\`: ${esc(e.message)}`);
  }
  return L.join('\n') + '\n';
}
